apiVersion: v1
kind: Service
metadata:
  name: hackhathon-web
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: hackhathon-web
  namespace: default
subsets:
  - addresses:
      - ip: 172.26.10.153
    ports:
      - name: http
        port: 8080
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackhathon-web
  namespace: default
spec:
  rules:
    - host: hackhathon.69d5c46af2ab61f5dd649c62.servers.onzeabur.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hackhathon-web
                port:
                  number: 80
